### ISSUE TITLE
Compilation Failure on Mac OSX

### ISSUE THREAD

**Issue by ibillabong** [SoapCanFly/tinyPornManager#8]
Hello! I'm unable to compile with Maven and can't find the solution. Here's the error:

Compilation failure
../tinyPornManager/src/main/java/org/tinymediamanager/scraper/pornhub/v1/PornhubMovieMetadataProvider.java:[203,76] incompatible types: java.nio.charset.Charset cannot be converted to java.lang.String

Any possible solutions?

**Comment by scoooooott** [comment]
Seem like you are using temurin JDK or something else. try Oracle jdk 1.8 or modify source code like below
```java
// from this
// params.put("search", URLEncoder.encode(searchString, StandardCharsets.UTF_8));
// to below
params.put("search", URLEncoder.encode(searchString, "UTF-8"));
```

**Comment by ibillabong** [comment]
Great - that fixed it! Thank you.
